version: '3.8'

services:
  web:
    build: .
    command: python3 web_app.py
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db

  tracker:
    build: .
    command: python3 run_tracker.py
    restart: "no"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: pcr_postgres
    environment:
      POSTGRES_USER: pcr_user
      POSTGRES_PASSWORD: pcr_pass
      POSTGRES_DB: pcr_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:

